### ISSUE TITLE
LaserScan visualization plugin

### ISSUE THREAD

**Issue by Sarath18** [Sarath18/ign-rviz#17]
Create `sensor_msgs/msg/LaserScan` visualization for ign-rviz using ignition rendering and ROS2

**Comment by chapulina** [comment]
This and #19 sound like could use https://github.com/ignitionrobotics/ign-rendering/issues/84 and avoid duplication of efforts.

CC @mihirk284 and @iche033

**Comment by Sarath18** [comment]
I talked with my mentor @ahcorde and I believe we decided to go ahead (in review) with the current implementation of LaserScan and then integrate the LidarVisual that @mihirk284 is working on,  once that is done. Hence the ticket #19.

**Comment by chapulina** [comment]
Cool, that makes sense. I see you're using marker points, which should work great for point clouds :smile:
